[theme]

base="light"
primaryColor="#16423C"
#secondaryBackgroundColor="#EFDDB8"
textColor="#16423C"

#primaryColor="#F63366"
backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
font="sans serif"

#16423C
#E2C27B
#EFDDB8
