[theme]

base="light"
primaryColor="#16423C"
secondaryBackgroundColor="#FCDE70"
textColor="#16423C"

#primaryColor="#F63366"
backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
font="sans serif"